
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author abbey
 */
public class WORDLE extends javax.swing.JFrame {

    /**
     * Creates new form WORDLE
     */
    public WORDLE() {
        initComponents();
        W1Letter1.setText("");
        W1Letter2.setText("");
        W1Letter3.setText("");
        W1Letter4.setText("");
        W1Letter5.setText("");
        W2Letter1.setText("");
        W2Letter3.setText("");
        W2Letter2.setText("");
        W2Letter4.setText("");
        W2Letter5.setText("");
        W3Letter1.setText("");
        W3Letter2.setText("");
        W3Letter3.setText("");
        W3Letter4.setText("");
        W3Letter5.setText("");
        W4Letter1.setText("");
        W4Letter2.setText("");
        W4Letter3.setText("");
        W4Letter4.setText("");
        W4Letter5.setText("");
        W5Letter1.setText("");
        W5Letter2.setText("");
        W5Letter3.setText("");
        W5Letter4.setText("");
        W5Letter5.setText("");
        W6Letter1.setText("");
        W6Letter3.setText("");
        W6Letter4.setText("");
        W6Letter5.setText("");
        W6Letter2.setText("");
        RESEULTTXT.setText("");
    }
     int wordCount = 0;
     static String P1Wrd;
     static String P2Wrd;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Wrd1L1 = new javax.swing.JPanel();
        W1Letter1 = new javax.swing.JLabel();
        Wrd2L4 = new javax.swing.JPanel();
        W2Letter4 = new javax.swing.JLabel();
        Wrd1L2 = new javax.swing.JPanel();
        W1Letter2 = new javax.swing.JLabel();
        Wrd2L5 = new javax.swing.JPanel();
        W2Letter5 = new javax.swing.JLabel();
        Wrd1L3 = new javax.swing.JPanel();
        W1Letter3 = new javax.swing.JLabel();
        Wrd3L1 = new javax.swing.JPanel();
        W3Letter1 = new javax.swing.JLabel();
        Wrd1L4 = new javax.swing.JPanel();
        W1Letter4 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Wrd3L2 = new javax.swing.JPanel();
        W3Letter2 = new javax.swing.JLabel();
        Wrd1L5 = new javax.swing.JPanel();
        W1Letter5 = new javax.swing.JLabel();
        PLY1GUE = new javax.swing.JLabel();
        Wrd6L5 = new javax.swing.JPanel();
        W6Letter5 = new javax.swing.JLabel();
        P1Input = new javax.swing.JTextField();
        Wrd3L3 = new javax.swing.JPanel();
        W3Letter3 = new javax.swing.JLabel();
        P1Confirm = new javax.swing.JButton();
        Wrd4L3 = new javax.swing.JPanel();
        W4Letter3 = new javax.swing.JLabel();
        PLY2GUE = new javax.swing.JLabel();
        P2Input = new javax.swing.JTextField();
        Wrd5L3 = new javax.swing.JPanel();
        W5Letter3 = new javax.swing.JLabel();
        P2Confirm = new javax.swing.JButton();
        Wrd6L4 = new javax.swing.JPanel();
        W6Letter4 = new javax.swing.JLabel();
        Wrd4L2 = new javax.swing.JPanel();
        W4Letter2 = new javax.swing.JLabel();
        Wrd3L4 = new javax.swing.JPanel();
        W3Letter4 = new javax.swing.JLabel();
        Wrd3L5 = new javax.swing.JPanel();
        W3Letter5 = new javax.swing.JLabel();
        Wrd4L5 = new javax.swing.JPanel();
        W4Letter5 = new javax.swing.JLabel();
        Wrd5L5 = new javax.swing.JPanel();
        W5Letter5 = new javax.swing.JLabel();
        Wrd5L2 = new javax.swing.JPanel();
        W5Letter2 = new javax.swing.JLabel();
        Wrd6L2 = new javax.swing.JPanel();
        W6Letter2 = new javax.swing.JLabel();
        Wrd2L1 = new javax.swing.JPanel();
        W2Letter1 = new javax.swing.JLabel();
        Wrd6L3 = new javax.swing.JPanel();
        W6Letter3 = new javax.swing.JLabel();
        Wrd2L3 = new javax.swing.JPanel();
        W2Letter3 = new javax.swing.JLabel();
        Wrd4L1 = new javax.swing.JPanel();
        W4Letter1 = new javax.swing.JLabel();
        Wrd2L2 = new javax.swing.JPanel();
        W2Letter2 = new javax.swing.JLabel();
        Wrd5L1 = new javax.swing.JPanel();
        W5Letter1 = new javax.swing.JLabel();
        Wrd4L4 = new javax.swing.JPanel();
        W4Letter4 = new javax.swing.JLabel();
        Wrd6L1 = new javax.swing.JPanel();
        W6Letter1 = new javax.swing.JLabel();
        Wrd5L4 = new javax.swing.JPanel();
        W5Letter4 = new javax.swing.JLabel();
        RESEULTTXT = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        EXIT = new javax.swing.JMenuItem();
        EDIT = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(70, 67));
        setMinimumSize(new java.awt.Dimension(70, 67));

        Wrd1L1.setBackground(new java.awt.Color(153, 153, 153));
        Wrd1L1.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd1L1.setMinimumSize(new java.awt.Dimension(70, 67));

        W1Letter1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W1Letter1.setText("A");

        javax.swing.GroupLayout Wrd1L1Layout = new javax.swing.GroupLayout(Wrd1L1);
        Wrd1L1.setLayout(Wrd1L1Layout);
        Wrd1L1Layout.setHorizontalGroup(
            Wrd1L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd1L1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W1Letter1)
                .addGap(27, 27, 27))
        );
        Wrd1L1Layout.setVerticalGroup(
            Wrd1L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd1L1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W1Letter1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd2L4.setBackground(new java.awt.Color(153, 153, 153));
        Wrd2L4.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd2L4.setMinimumSize(new java.awt.Dimension(70, 67));

        W2Letter4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W2Letter4.setText("A");

        javax.swing.GroupLayout Wrd2L4Layout = new javax.swing.GroupLayout(Wrd2L4);
        Wrd2L4.setLayout(Wrd2L4Layout);
        Wrd2L4Layout.setHorizontalGroup(
            Wrd2L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd2L4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(W2Letter4)
                .addGap(29, 29, 29))
        );
        Wrd2L4Layout.setVerticalGroup(
            Wrd2L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd2L4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W2Letter4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd1L2.setBackground(new java.awt.Color(153, 153, 153));
        Wrd1L2.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd1L2.setMinimumSize(new java.awt.Dimension(70, 67));

        W1Letter2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W1Letter2.setText("A");

        javax.swing.GroupLayout Wrd1L2Layout = new javax.swing.GroupLayout(Wrd1L2);
        Wrd1L2.setLayout(Wrd1L2Layout);
        Wrd1L2Layout.setHorizontalGroup(
            Wrd1L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd1L2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(W1Letter2)
                .addGap(27, 27, 27))
        );
        Wrd1L2Layout.setVerticalGroup(
            Wrd1L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd1L2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W1Letter2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd2L5.setBackground(new java.awt.Color(153, 153, 153));
        Wrd2L5.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd2L5.setMinimumSize(new java.awt.Dimension(70, 67));

        W2Letter5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W2Letter5.setText("A");

        javax.swing.GroupLayout Wrd2L5Layout = new javax.swing.GroupLayout(Wrd2L5);
        Wrd2L5.setLayout(Wrd2L5Layout);
        Wrd2L5Layout.setHorizontalGroup(
            Wrd2L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd2L5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W2Letter5)
                .addGap(27, 27, 27))
        );
        Wrd2L5Layout.setVerticalGroup(
            Wrd2L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd2L5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W2Letter5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd1L3.setBackground(new java.awt.Color(153, 153, 153));
        Wrd1L3.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd1L3.setMinimumSize(new java.awt.Dimension(70, 67));

        W1Letter3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W1Letter3.setText("A");

        javax.swing.GroupLayout Wrd1L3Layout = new javax.swing.GroupLayout(Wrd1L3);
        Wrd1L3.setLayout(Wrd1L3Layout);
        Wrd1L3Layout.setHorizontalGroup(
            Wrd1L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd1L3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W1Letter3)
                .addGap(27, 27, 27))
        );
        Wrd1L3Layout.setVerticalGroup(
            Wrd1L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd1L3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W1Letter3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd3L1.setBackground(new java.awt.Color(153, 153, 153));
        Wrd3L1.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd3L1.setMinimumSize(new java.awt.Dimension(70, 67));

        W3Letter1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W3Letter1.setText("A");

        javax.swing.GroupLayout Wrd3L1Layout = new javax.swing.GroupLayout(Wrd3L1);
        Wrd3L1.setLayout(Wrd3L1Layout);
        Wrd3L1Layout.setHorizontalGroup(
            Wrd3L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd3L1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(W3Letter1)
                .addGap(27, 27, 27))
        );
        Wrd3L1Layout.setVerticalGroup(
            Wrd3L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd3L1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W3Letter1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd1L4.setBackground(new java.awt.Color(153, 153, 153));
        Wrd1L4.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd1L4.setMinimumSize(new java.awt.Dimension(70, 67));

        W1Letter4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W1Letter4.setText("A");

        javax.swing.GroupLayout Wrd1L4Layout = new javax.swing.GroupLayout(Wrd1L4);
        Wrd1L4.setLayout(Wrd1L4Layout);
        Wrd1L4Layout.setHorizontalGroup(
            Wrd1L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd1L4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(W1Letter4)
                .addGap(27, 27, 27))
        );
        Wrd1L4Layout.setVerticalGroup(
            Wrd1L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd1L4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W1Letter4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Title.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Wordle 2.0");

        Wrd3L2.setBackground(new java.awt.Color(153, 153, 153));
        Wrd3L2.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd3L2.setMinimumSize(new java.awt.Dimension(70, 67));

        W3Letter2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W3Letter2.setText("A");

        javax.swing.GroupLayout Wrd3L2Layout = new javax.swing.GroupLayout(Wrd3L2);
        Wrd3L2.setLayout(Wrd3L2Layout);
        Wrd3L2Layout.setHorizontalGroup(
            Wrd3L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd3L2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(W3Letter2)
                .addGap(27, 27, 27))
        );
        Wrd3L2Layout.setVerticalGroup(
            Wrd3L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd3L2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W3Letter2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd1L5.setBackground(new java.awt.Color(153, 153, 153));
        Wrd1L5.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd1L5.setMinimumSize(new java.awt.Dimension(70, 67));

        W1Letter5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W1Letter5.setText("A");

        javax.swing.GroupLayout Wrd1L5Layout = new javax.swing.GroupLayout(Wrd1L5);
        Wrd1L5.setLayout(Wrd1L5Layout);
        Wrd1L5Layout.setHorizontalGroup(
            Wrd1L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd1L5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W1Letter5)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Wrd1L5Layout.setVerticalGroup(
            Wrd1L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd1L5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W1Letter5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PLY1GUE.setText("PLAYER1 WORD");

        Wrd6L5.setBackground(new java.awt.Color(153, 153, 153));
        Wrd6L5.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd6L5.setMinimumSize(new java.awt.Dimension(70, 67));

        W6Letter5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W6Letter5.setText("A");

        javax.swing.GroupLayout Wrd6L5Layout = new javax.swing.GroupLayout(Wrd6L5);
        Wrd6L5.setLayout(Wrd6L5Layout);
        Wrd6L5Layout.setHorizontalGroup(
            Wrd6L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd6L5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(W6Letter5)
                .addGap(27, 27, 27))
        );
        Wrd6L5Layout.setVerticalGroup(
            Wrd6L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd6L5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W6Letter5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd3L3.setBackground(new java.awt.Color(153, 153, 153));
        Wrd3L3.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd3L3.setMinimumSize(new java.awt.Dimension(70, 67));

        W3Letter3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W3Letter3.setText("A");

        javax.swing.GroupLayout Wrd3L3Layout = new javax.swing.GroupLayout(Wrd3L3);
        Wrd3L3.setLayout(Wrd3L3Layout);
        Wrd3L3Layout.setHorizontalGroup(
            Wrd3L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd3L3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(W3Letter3)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        Wrd3L3Layout.setVerticalGroup(
            Wrd3L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd3L3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W3Letter3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        P1Confirm.setText("Confirm");
        P1Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ConfirmActionPerformed(evt);
            }
        });

        Wrd4L3.setBackground(new java.awt.Color(153, 153, 153));
        Wrd4L3.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd4L3.setMinimumSize(new java.awt.Dimension(70, 67));

        W4Letter3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W4Letter3.setText("A");

        javax.swing.GroupLayout Wrd4L3Layout = new javax.swing.GroupLayout(Wrd4L3);
        Wrd4L3.setLayout(Wrd4L3Layout);
        Wrd4L3Layout.setHorizontalGroup(
            Wrd4L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd4L3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W4Letter3)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Wrd4L3Layout.setVerticalGroup(
            Wrd4L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd4L3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W4Letter3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PLY2GUE.setText("PLAYER2 GUESS");

        P2Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2InputActionPerformed(evt);
            }
        });

        Wrd5L3.setBackground(new java.awt.Color(153, 153, 153));
        Wrd5L3.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd5L3.setMinimumSize(new java.awt.Dimension(70, 67));

        W5Letter3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W5Letter3.setText("A");

        javax.swing.GroupLayout Wrd5L3Layout = new javax.swing.GroupLayout(Wrd5L3);
        Wrd5L3.setLayout(Wrd5L3Layout);
        Wrd5L3Layout.setHorizontalGroup(
            Wrd5L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd5L3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W5Letter3)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Wrd5L3Layout.setVerticalGroup(
            Wrd5L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd5L3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W5Letter3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        P2Confirm.setText("Confirm");
        P2Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2ConfirmActionPerformed(evt);
            }
        });

        Wrd6L4.setBackground(new java.awt.Color(153, 153, 153));
        Wrd6L4.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd6L4.setMinimumSize(new java.awt.Dimension(70, 67));

        W6Letter4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W6Letter4.setText("A");

        javax.swing.GroupLayout Wrd6L4Layout = new javax.swing.GroupLayout(Wrd6L4);
        Wrd6L4.setLayout(Wrd6L4Layout);
        Wrd6L4Layout.setHorizontalGroup(
            Wrd6L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd6L4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W6Letter4)
                .addGap(27, 27, 27))
        );
        Wrd6L4Layout.setVerticalGroup(
            Wrd6L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd6L4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W6Letter4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd4L2.setBackground(new java.awt.Color(153, 153, 153));
        Wrd4L2.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd4L2.setMinimumSize(new java.awt.Dimension(70, 67));

        W4Letter2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W4Letter2.setText("A");

        javax.swing.GroupLayout Wrd4L2Layout = new javax.swing.GroupLayout(Wrd4L2);
        Wrd4L2.setLayout(Wrd4L2Layout);
        Wrd4L2Layout.setHorizontalGroup(
            Wrd4L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd4L2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(W4Letter2)
                .addGap(27, 27, 27))
        );
        Wrd4L2Layout.setVerticalGroup(
            Wrd4L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd4L2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W4Letter2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd3L4.setBackground(new java.awt.Color(153, 153, 153));
        Wrd3L4.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd3L4.setMinimumSize(new java.awt.Dimension(70, 67));

        W3Letter4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W3Letter4.setText("A");

        javax.swing.GroupLayout Wrd3L4Layout = new javax.swing.GroupLayout(Wrd3L4);
        Wrd3L4.setLayout(Wrd3L4Layout);
        Wrd3L4Layout.setHorizontalGroup(
            Wrd3L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd3L4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W3Letter4)
                .addGap(27, 27, 27))
        );
        Wrd3L4Layout.setVerticalGroup(
            Wrd3L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd3L4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W3Letter4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd3L5.setBackground(new java.awt.Color(153, 153, 153));
        Wrd3L5.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd3L5.setMinimumSize(new java.awt.Dimension(70, 67));

        W3Letter5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W3Letter5.setText("A");

        javax.swing.GroupLayout Wrd3L5Layout = new javax.swing.GroupLayout(Wrd3L5);
        Wrd3L5.setLayout(Wrd3L5Layout);
        Wrd3L5Layout.setHorizontalGroup(
            Wrd3L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd3L5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W3Letter5)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Wrd3L5Layout.setVerticalGroup(
            Wrd3L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd3L5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W3Letter5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd4L5.setBackground(new java.awt.Color(153, 153, 153));
        Wrd4L5.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd4L5.setMinimumSize(new java.awt.Dimension(70, 67));

        W4Letter5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W4Letter5.setText("A");

        javax.swing.GroupLayout Wrd4L5Layout = new javax.swing.GroupLayout(Wrd4L5);
        Wrd4L5.setLayout(Wrd4L5Layout);
        Wrd4L5Layout.setHorizontalGroup(
            Wrd4L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd4L5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W4Letter5)
                .addGap(27, 27, 27))
        );
        Wrd4L5Layout.setVerticalGroup(
            Wrd4L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd4L5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W4Letter5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd5L5.setBackground(new java.awt.Color(153, 153, 153));
        Wrd5L5.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd5L5.setMinimumSize(new java.awt.Dimension(70, 67));

        W5Letter5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W5Letter5.setText("A");

        javax.swing.GroupLayout Wrd5L5Layout = new javax.swing.GroupLayout(Wrd5L5);
        Wrd5L5.setLayout(Wrd5L5Layout);
        Wrd5L5Layout.setHorizontalGroup(
            Wrd5L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd5L5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W5Letter5)
                .addGap(27, 27, 27))
        );
        Wrd5L5Layout.setVerticalGroup(
            Wrd5L5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd5L5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W5Letter5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd5L2.setBackground(new java.awt.Color(153, 153, 153));
        Wrd5L2.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd5L2.setMinimumSize(new java.awt.Dimension(70, 67));

        W5Letter2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W5Letter2.setText("A");

        javax.swing.GroupLayout Wrd5L2Layout = new javax.swing.GroupLayout(Wrd5L2);
        Wrd5L2.setLayout(Wrd5L2Layout);
        Wrd5L2Layout.setHorizontalGroup(
            Wrd5L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd5L2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(W5Letter2)
                .addGap(27, 27, 27))
        );
        Wrd5L2Layout.setVerticalGroup(
            Wrd5L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd5L2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W5Letter2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd6L2.setBackground(new java.awt.Color(153, 153, 153));
        Wrd6L2.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd6L2.setMinimumSize(new java.awt.Dimension(70, 67));

        W6Letter2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W6Letter2.setText("A");

        javax.swing.GroupLayout Wrd6L2Layout = new javax.swing.GroupLayout(Wrd6L2);
        Wrd6L2.setLayout(Wrd6L2Layout);
        Wrd6L2Layout.setHorizontalGroup(
            Wrd6L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd6L2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W6Letter2)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Wrd6L2Layout.setVerticalGroup(
            Wrd6L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd6L2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W6Letter2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd2L1.setBackground(new java.awt.Color(153, 153, 153));
        Wrd2L1.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd2L1.setMinimumSize(new java.awt.Dimension(70, 67));

        W2Letter1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W2Letter1.setText("A");

        javax.swing.GroupLayout Wrd2L1Layout = new javax.swing.GroupLayout(Wrd2L1);
        Wrd2L1.setLayout(Wrd2L1Layout);
        Wrd2L1Layout.setHorizontalGroup(
            Wrd2L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd2L1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W2Letter1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Wrd2L1Layout.setVerticalGroup(
            Wrd2L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd2L1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W2Letter1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd6L3.setBackground(new java.awt.Color(153, 153, 153));
        Wrd6L3.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd6L3.setMinimumSize(new java.awt.Dimension(70, 67));

        W6Letter3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W6Letter3.setText("A");

        javax.swing.GroupLayout Wrd6L3Layout = new javax.swing.GroupLayout(Wrd6L3);
        Wrd6L3.setLayout(Wrd6L3Layout);
        Wrd6L3Layout.setHorizontalGroup(
            Wrd6L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd6L3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(W6Letter3)
                .addGap(27, 27, 27))
        );
        Wrd6L3Layout.setVerticalGroup(
            Wrd6L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd6L3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W6Letter3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd2L3.setBackground(new java.awt.Color(153, 153, 153));
        Wrd2L3.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd2L3.setMinimumSize(new java.awt.Dimension(70, 67));

        W2Letter3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W2Letter3.setText("A");

        javax.swing.GroupLayout Wrd2L3Layout = new javax.swing.GroupLayout(Wrd2L3);
        Wrd2L3.setLayout(Wrd2L3Layout);
        Wrd2L3Layout.setHorizontalGroup(
            Wrd2L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd2L3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W2Letter3)
                .addGap(27, 27, 27))
        );
        Wrd2L3Layout.setVerticalGroup(
            Wrd2L3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd2L3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W2Letter3)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd4L1.setBackground(new java.awt.Color(153, 153, 153));
        Wrd4L1.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd4L1.setMinimumSize(new java.awt.Dimension(70, 67));

        W4Letter1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W4Letter1.setText("A");

        javax.swing.GroupLayout Wrd4L1Layout = new javax.swing.GroupLayout(Wrd4L1);
        Wrd4L1.setLayout(Wrd4L1Layout);
        Wrd4L1Layout.setHorizontalGroup(
            Wrd4L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Wrd4L1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(W4Letter1)
                .addGap(27, 27, 27))
        );
        Wrd4L1Layout.setVerticalGroup(
            Wrd4L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd4L1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W4Letter1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd2L2.setBackground(new java.awt.Color(153, 153, 153));
        Wrd2L2.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd2L2.setMinimumSize(new java.awt.Dimension(70, 67));

        W2Letter2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W2Letter2.setText("A");

        javax.swing.GroupLayout Wrd2L2Layout = new javax.swing.GroupLayout(Wrd2L2);
        Wrd2L2.setLayout(Wrd2L2Layout);
        Wrd2L2Layout.setHorizontalGroup(
            Wrd2L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd2L2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W2Letter2)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Wrd2L2Layout.setVerticalGroup(
            Wrd2L2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd2L2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W2Letter2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd5L1.setBackground(new java.awt.Color(153, 153, 153));
        Wrd5L1.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd5L1.setMinimumSize(new java.awt.Dimension(70, 67));

        W5Letter1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W5Letter1.setText("A");

        javax.swing.GroupLayout Wrd5L1Layout = new javax.swing.GroupLayout(Wrd5L1);
        Wrd5L1.setLayout(Wrd5L1Layout);
        Wrd5L1Layout.setHorizontalGroup(
            Wrd5L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd5L1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W5Letter1)
                .addGap(27, 27, 27))
        );
        Wrd5L1Layout.setVerticalGroup(
            Wrd5L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd5L1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W5Letter1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd4L4.setBackground(new java.awt.Color(153, 153, 153));
        Wrd4L4.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd4L4.setMinimumSize(new java.awt.Dimension(70, 67));

        W4Letter4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W4Letter4.setText("A");

        javax.swing.GroupLayout Wrd4L4Layout = new javax.swing.GroupLayout(Wrd4L4);
        Wrd4L4.setLayout(Wrd4L4Layout);
        Wrd4L4Layout.setHorizontalGroup(
            Wrd4L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd4L4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W4Letter4)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Wrd4L4Layout.setVerticalGroup(
            Wrd4L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd4L4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W4Letter4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd6L1.setBackground(new java.awt.Color(153, 153, 153));
        Wrd6L1.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd6L1.setMinimumSize(new java.awt.Dimension(70, 67));

        W6Letter1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W6Letter1.setText("A");

        javax.swing.GroupLayout Wrd6L1Layout = new javax.swing.GroupLayout(Wrd6L1);
        Wrd6L1.setLayout(Wrd6L1Layout);
        Wrd6L1Layout.setHorizontalGroup(
            Wrd6L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd6L1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W6Letter1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Wrd6L1Layout.setVerticalGroup(
            Wrd6L1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd6L1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W6Letter1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Wrd5L4.setBackground(new java.awt.Color(153, 153, 153));
        Wrd5L4.setMaximumSize(new java.awt.Dimension(70, 67));
        Wrd5L4.setMinimumSize(new java.awt.Dimension(70, 67));

        W5Letter4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        W5Letter4.setText("A");

        javax.swing.GroupLayout Wrd5L4Layout = new javax.swing.GroupLayout(Wrd5L4);
        Wrd5L4.setLayout(Wrd5L4Layout);
        Wrd5L4Layout.setHorizontalGroup(
            Wrd5L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd5L4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(W5Letter4)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Wrd5L4Layout.setVerticalGroup(
            Wrd5L4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Wrd5L4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(W5Letter4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        RESEULTTXT.setFont(new java.awt.Font("Century", 1, 24)); // NOI18N
        RESEULTTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        File.setText("File");

        EXIT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        File.add(EXIT);

        MenuBar.add(File);

        EDIT.setText("Edit");
        MenuBar.add(EDIT);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Wrd3L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Wrd3L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(Wrd3L3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(Wrd3L4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(Wrd3L5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Wrd1L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Wrd1L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(Wrd1L3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(Wrd1L4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(Wrd1L5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Wrd2L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(Wrd2L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(Wrd2L3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(Wrd2L4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(7, 7, 7)
                            .addComponent(Wrd2L5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PLY1GUE)
                                .addComponent(PLY2GUE))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(P2Input)
                                .addComponent(P1Input, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(P1Confirm)
                                .addComponent(P2Confirm))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Wrd4L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd4L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd4L3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd4L4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd4L5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Wrd5L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd5L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd5L3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd5L4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd5L5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Wrd6L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd6L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd6L3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(Wrd6L4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Wrd6L5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RESEULTTXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PLY1GUE)
                    .addComponent(P1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P1Confirm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PLY2GUE)
                    .addComponent(P2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P2Confirm))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Wrd1L5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wrd1L4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wrd1L3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wrd1L2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wrd1L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Wrd2L5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Wrd3L5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Wrd2L3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Wrd2L4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Wrd3L3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Wrd3L4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Wrd2L2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Wrd3L2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Wrd2L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Wrd3L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Wrd4L5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Wrd5L5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Wrd4L3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Wrd4L4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Wrd5L3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Wrd5L4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Wrd4L2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Wrd5L2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Wrd4L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Wrd5L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Wrd6L2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Wrd6L5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Wrd6L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Wrd6L3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Wrd6L4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(RESEULTTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P1ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ConfirmActionPerformed

        this.P1Wrd = (P1Input.getText());
        P1Input.setText("");

        WORDLECLASS Player1Word = new WORDLECLASS(P1Wrd);
    }//GEN-LAST:event_P1ConfirmActionPerformed

    private void P2InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P2InputActionPerformed

    private void P2ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2ConfirmActionPerformed
        wordCount ++;
        this.P2Wrd = (P2Input.getText().toUpperCase());

        P2Input.setText("");

        WORDLECLASS Player2Word = new WORDLECLASS(P1Wrd);
        int[] result = Player2Word.checkPlayer2Word(P2Wrd);

        // 1st word entered
        if (wordCount == 1)
        {
            W1Letter1.setText(P2Wrd.substring(0, 1));//prints out first letetr

            if (result[0] == 3) //checks to see if letter matches the first Players word
            {
                Wrd1L1.setBackground(Color.GREEN);
            }
            else if (result[0] == 2)
            {
                Wrd1L1.setBackground(Color.YELLOW);
            }

            W1Letter2.setText(P2Wrd.substring(1, 2));

            if (result[1] == 3)
            {
                Wrd1L2.setBackground(Color.GREEN);
            }
            else if (result[1] == 2)
            {
                Wrd1L2.setBackground(Color.YELLOW);
            }

            W1Letter3.setText(P2Wrd.substring(2, 3));

            if (result[2] == 3)
            {
                Wrd1L3.setBackground(Color.GREEN);
            }
            else if (result[2] == 2)
            {
                Wrd1L3.setBackground(Color.YELLOW);
            }

            W1Letter4.setText(P2Wrd.substring(3, 4));

            if (result[3] == 3)
            {
                Wrd1L4.setBackground(Color.GREEN);
            }
            else if (result[3] == 2)
            {
                Wrd1L4.setBackground(Color.YELLOW);
            }

            W1Letter5.setText(P2Wrd.substring(4, 5));

            if (result[4] == 3)
            {
                Wrd1L5.setBackground(Color.GREEN);
            }
            else if (result[4] == 2)
            {
                Wrd1L5.setBackground(Color.YELLOW);
            }
        }
        if (P2Wrd.equals(P1Wrd)) {
            RESEULTTXT.setText("Word Matches!");
        }

        // 2nd word entered
        else if (wordCount == 2)
        {

            W2Letter1.setText(P2Wrd.substring(0, 1));
            if (result[0] == 3)
            {
                Wrd2L1.setBackground(Color.GREEN);
            }
            else if (result[0] == 2)
            {
                Wrd2L1.setBackground(Color.YELLOW);
            }
            W2Letter2.setText(P2Wrd.substring(1, 2));
            if (result[1] == 3)
            {
                Wrd2L2.setBackground(Color.GREEN);
            }
            else if (result[1] == 2)
            {
                Wrd2L2.setBackground(Color.YELLOW);
            }
            W2Letter3.setText(P2Wrd.substring(2, 3));
            if (result[2] == 3)
            {
                Wrd2L3.setBackground(Color.GREEN);
            }
            else if (result[2] == 2)
            {
                Wrd2L3.setBackground(Color.YELLOW);
            }
            W2Letter4.setText(P2Wrd.substring(3, 4));
            if (result[3] == 3)
            {
                Wrd2L4.setBackground(Color.GREEN);
            }
            else if (result[3] == 2)
            {
                Wrd2L4.setBackground(Color.YELLOW);
            }
            W2Letter5.setText(P2Wrd.substring(4, 5));
            if (result[4] == 3)
            {
                Wrd2L5.setBackground(Color.GREEN);
            }
            else if (result[4] == 2)
            {
                Wrd2L5.setBackground(Color.YELLOW);
            }
        }

        // 3rd word entered
        else if (wordCount == 3)
        {
            W3Letter1.setText(P2Wrd.substring(0, 1));
            if (result[0] == 3)
            {
                Wrd3L1.setBackground(Color.GREEN);
            }
            else if (result[0] == 2)
            {
                Wrd3L1.setBackground(Color.YELLOW);
            }
            W3Letter2.setText(P2Wrd.substring(1, 2));
            if (result[1] == 3)
            {
                Wrd3L2.setBackground(Color.GREEN);
            }
            else if (result[1] == 2)
            {
                Wrd3L2.setBackground(Color.YELLOW);
            }
            W3Letter3.setText(P2Wrd.substring(2, 3));
            if (result[2] == 3)
            {
                Wrd3L3.setBackground(Color.GREEN);
            }
            else if (result[2] == 2)
            {
                Wrd3L3.setBackground(Color.YELLOW);
            }
            W3Letter4.setText(P2Wrd.substring(3, 4));
            if (result[3] == 3)
            {
                Wrd3L4.setBackground(Color.GREEN);
            }
            else if (result[3] == 2)
            {
                Wrd3L4.setBackground(Color.YELLOW);
            }
            W3Letter5.setText(P2Wrd.substring(4, 5));
            if (result[4] == 3)
            {
                Wrd3L5.setBackground(Color.GREEN);
            }
            else if (result[4] == 2)
            {
                Wrd3L5.setBackground(Color.YELLOW);
            }
        }

        //4th word entered
        else if (wordCount == 4)
        {
            W4Letter1.setText(P2Wrd.substring(0, 1));
            if (result[0] == 3)
            {
                Wrd4L1.setBackground(Color.GREEN);
            }
            else if (result[0] == 2)
            {
                Wrd4L1.setBackground(Color.YELLOW);
            }
            W4Letter2.setText(P2Wrd.substring(1, 2));

            if (result[1] == 3)
            {
                Wrd4L2.setBackground(Color.GREEN);
            }
            else if (result[1] == 2)
            {
                Wrd4L2.setBackground(Color.YELLOW);
            }
            W4Letter3.setText(P2Wrd.substring(2, 3));

            if (result[2] == 3)
            {
                Wrd4L3.setBackground(Color.GREEN);
            }
            else if (result[2] == 2)
            {
                Wrd4L3.setBackground(Color.YELLOW);
            }
            W4Letter4.setText(P2Wrd.substring(3, 4));

            if (result[3] == 3)
            {
                Wrd4L4.setBackground(Color.GREEN);
            }
            else if (result[3] == 2)
            {
                Wrd4L4.setBackground(Color.YELLOW);
            }
            W4Letter5.setText(P2Wrd.substring(4, 5));

            if (result[4] == 3)
            {
                Wrd4L5.setBackground(Color.GREEN);
            }
            else if (result[4] == 2)
            {
                Wrd4L5.setBackground(Color.YELLOW);
            }
        }

        // 5th word entered
        else if (wordCount == 5)
        {
            W5Letter1.setText(P2Wrd.substring(0, 1));
            if (result[0] == 3)
            {
                Wrd5L1.setBackground(Color.GREEN);
            }
            else if (result[0] == 2)
            {
                Wrd5L1.setBackground(Color.YELLOW);
            }
            W5Letter2.setText(P2Wrd.substring(1, 2));
            if (result[1] == 3)
            {
                Wrd5L2.setBackground(Color.GREEN);
            }
            else if (result[1] == 2)
            {
                Wrd5L2.setBackground(Color.YELLOW);
            }
            W5Letter3.setText(P2Wrd.substring(2, 3));
            if (result[2] == 3)
            {
                Wrd5L3.setBackground(Color.GREEN);
            }
            else if (result[2] == 2)
            {
                Wrd5L3.setBackground(Color.YELLOW);
            }
            W5Letter4.setText(P2Wrd.substring(3, 4));
            if (result[3] == 3)
            {
                Wrd5L4.setBackground(Color.GREEN);
            }
            else if (result[3] == 2)
            {
                Wrd5L4.setBackground(Color.YELLOW);
            }
            W5Letter5.setText(P2Wrd.substring(4, 5));
            if (result[4] == 3)
            {
                Wrd5L5.setBackground(Color.GREEN);
            }
            else if (result[4] == 2)
            {
                Wrd5L5.setBackground(Color.YELLOW);
            }
        }

        // 6th word entered
        else if (wordCount == 6)
        {
            W6Letter1.setText(P2Wrd.substring(0, 1));
            if (result[0] == 3)
            {
                Wrd6L1.setBackground(Color.GREEN);
            }
            else if (result[0] == 2)
            {
                Wrd6L1.setBackground(Color.YELLOW);
            }
            W6Letter2.setText(P2Wrd.substring(1, 2));
            if (result[1] == 3)
            {
                Wrd6L2.setBackground(Color.GREEN);
            }
            else if (result[1] == 2)
            {
                Wrd6L2.setBackground(Color.YELLOW);
            }
            W6Letter3.setText(P2Wrd.substring(2, 3));
            if (result[2] == 3)
            {
                Wrd6L3.setBackground(Color.GREEN);
            }
            else if (result[2] == 2)
            {
                Wrd6L3.setBackground(Color.YELLOW);
            }
            W6Letter4.setText(P2Wrd.substring(3, 4));
            if (result[3] == 3)
            {
                Wrd6L4.setBackground(Color.GREEN);
            }
            else if (result[3] == 2)
            {
                Wrd6L4.setBackground(Color.YELLOW);
            }
            W6Letter5.setText(P2Wrd.substring(4, 5));
            if (result[4] == 3)
            {
                Wrd6L5.setBackground(Color.GREEN);
            }
            else if (result[4] == 2)
            {
                Wrd6L5.setBackground(Color.YELLOW);
            }
        }
    }//GEN-LAST:event_P2ConfirmActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WORDLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WORDLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WORDLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WORDLE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WORDLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EDIT;
    private javax.swing.JMenuItem EXIT;
    private javax.swing.JMenu File;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton P1Confirm;
    private javax.swing.JTextField P1Input;
    private javax.swing.JButton P2Confirm;
    private javax.swing.JTextField P2Input;
    private javax.swing.JLabel PLY1GUE;
    private javax.swing.JLabel PLY2GUE;
    private javax.swing.JLabel RESEULTTXT;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel W1Letter1;
    private javax.swing.JLabel W1Letter2;
    private javax.swing.JLabel W1Letter3;
    private javax.swing.JLabel W1Letter4;
    private javax.swing.JLabel W1Letter5;
    private javax.swing.JLabel W2Letter1;
    private javax.swing.JLabel W2Letter2;
    private javax.swing.JLabel W2Letter3;
    private javax.swing.JLabel W2Letter4;
    private javax.swing.JLabel W2Letter5;
    private javax.swing.JLabel W3Letter1;
    private javax.swing.JLabel W3Letter2;
    private javax.swing.JLabel W3Letter3;
    private javax.swing.JLabel W3Letter4;
    private javax.swing.JLabel W3Letter5;
    private javax.swing.JLabel W4Letter1;
    private javax.swing.JLabel W4Letter2;
    private javax.swing.JLabel W4Letter3;
    private javax.swing.JLabel W4Letter4;
    private javax.swing.JLabel W4Letter5;
    private javax.swing.JLabel W5Letter1;
    private javax.swing.JLabel W5Letter2;
    private javax.swing.JLabel W5Letter3;
    private javax.swing.JLabel W5Letter4;
    private javax.swing.JLabel W5Letter5;
    private javax.swing.JLabel W6Letter1;
    private javax.swing.JLabel W6Letter2;
    private javax.swing.JLabel W6Letter3;
    private javax.swing.JLabel W6Letter4;
    private javax.swing.JLabel W6Letter5;
    private javax.swing.JPanel Wrd1L1;
    private javax.swing.JPanel Wrd1L2;
    private javax.swing.JPanel Wrd1L3;
    private javax.swing.JPanel Wrd1L4;
    private javax.swing.JPanel Wrd1L5;
    private javax.swing.JPanel Wrd2L1;
    private javax.swing.JPanel Wrd2L2;
    private javax.swing.JPanel Wrd2L3;
    private javax.swing.JPanel Wrd2L4;
    private javax.swing.JPanel Wrd2L5;
    private javax.swing.JPanel Wrd3L1;
    private javax.swing.JPanel Wrd3L2;
    private javax.swing.JPanel Wrd3L3;
    private javax.swing.JPanel Wrd3L4;
    private javax.swing.JPanel Wrd3L5;
    private javax.swing.JPanel Wrd4L1;
    private javax.swing.JPanel Wrd4L2;
    private javax.swing.JPanel Wrd4L3;
    private javax.swing.JPanel Wrd4L4;
    private javax.swing.JPanel Wrd4L5;
    private javax.swing.JPanel Wrd5L1;
    private javax.swing.JPanel Wrd5L2;
    private javax.swing.JPanel Wrd5L3;
    private javax.swing.JPanel Wrd5L4;
    private javax.swing.JPanel Wrd5L5;
    private javax.swing.JPanel Wrd6L1;
    private javax.swing.JPanel Wrd6L2;
    private javax.swing.JPanel Wrd6L3;
    private javax.swing.JPanel Wrd6L4;
    private javax.swing.JPanel Wrd6L5;
    // End of variables declaration//GEN-END:variables
}
